export const EMOJI_AVATARS = {
  a: { emoji: require("@assets/avatars/🤩.webp"), color: "#B25C00FF" },
  b: { emoji: require("@assets/avatars/🐸.webp"), color: "#457240FF" },
  c: { emoji: require("@assets/avatars/🐈.webp"), color: "#8A5227FF" },
  d: { emoji: require("@assets/avatars/🐵.webp"), color: "#875E2BFF" },
  e: { emoji: require("@assets/avatars/💸.webp"), color: "#716C41FF" },
  f: { emoji: require("@assets/avatars/🍓.webp"), color: "#99181AFF" },
  g: { emoji: require("@assets/avatars/🍌.webp"), color: "#AD7F05FF" },
  h: { emoji: require("@assets/avatars/😶‍🌫️.webp"), color: "#696948FF" },
  i: { emoji: require("@assets/avatars/😹.webp"), color: "#B28000FF" },
  j: { emoji: require("@assets/avatars/🦓.webp"), color: "#5E5954FF" },
  k: { emoji: require("@assets/avatars/🍆.webp"), color: "#6E436AFF" },
  l: { emoji: require("@assets/avatars/🥵.webp"), color: "#AC3B05FF" },
  m: { emoji: require("@assets/avatars/💀.webp"), color: "#5A5A57FF" },
  n: { emoji: require("@assets/avatars/👽.webp"), color: "#515F60FF" },
  o: { emoji: require("@assets/avatars/☹️.webp"), color: "#B27900FF" },
  p: { emoji: require("@assets/avatars/😎.webp"), color: "#B27900FF" },
  q: { emoji: require("@assets/avatars/😈.webp"), color: "#762C86FF" },
  r: { emoji: require("@assets/avatars/🤖.webp"), color: "#426A6FFF" },
  s: { emoji: require("@assets/avatars/🎃.webp"), color: "#AA6C07FF" },
  t: { emoji: require("@assets/avatars/🍎.webp"), color: "#9F1314FF" },
  u: { emoji: require("@assets/avatars/🍅.webp"), color: "#9C3315FF" },
  v: { emoji: require("@assets/avatars/🥑.webp"), color: "#7E882AFF" },
  w: { emoji: require("@assets/avatars/⚽.webp"), color: "#595959FF" },
  x: { emoji: require("@assets/avatars/🥺.webp"), color: "#B27900FF" },
  y: { emoji: require("@assets/avatars/💪.webp"), color: "#B27900FF" },
  z: { emoji: require("@assets/avatars/🦷.webp"), color: "#705D42FF" },
  _: { emoji: require("@assets/avatars/👀.webp"), color: "#B25700FF" },
  "-": { emoji: require("@assets/avatars/🧠.webp"), color: "#AF0339FF" },
} as const;
